### ISSUE TITLE
XmlSummary for methods are taken from "Hub type" instead of method  

### ISSUE THREAD

**Issue by hoaol** [RicoSuter/SigSpec#16]
Hi!
First I want to say that this is a very interesting project, at my company we are in the process of developing quite a lot of Signalr Services and have a need to get them documented in a structual way.
I have dowloaded the latest version and made some tests and like what I see :-) but I think I have found a little  bug...

In SigSpecGenerator.cs,  GenerateOperationAsync I think that
Description = await type.GetXmlSummaryAsync()
should be changed to 
Description = await method.GetXmlSummaryAsync()

**Comment by RicoSuter** [comment]
Sounds reasonable, can you create a PR?
