### ISSUE TITLE
Publishing on NuGet

### ISSUE THREAD

**Issue by diegofrata** [RicoSuter/SigSpec#20]
I have found this library to be quite useful, even though it's experimental. I published a build of it to NuGet so other people can play and experiment with it. I'm happy to either delist or add you to maintainers if you have any issues with it. Let me know.

**Comment by RicoSuter** [comment]
Please add me as maintainer so that i can set up a proper pipeline etc in the future. I assume you published it manually?

**Comment by diegofrata** [comment]
I've done it manually and it's far from proper. It's just so it can be used across different projects more easily. Added you there.

**Comment by RicoSuter** [comment]
Ok thanks. Also the dependencies are quite outdated (NJsonSchema). I dont know where this goes, currently I have enough work with NSwag...

**Comment by beorosz** [comment]
Hello Diego, could you please update the SigSpec.* packages on nuget? There was a small template modification and I'd like to use it.

**Comment by beorosz** [comment]
Hello @diegofrata ,could you please update the SigSpec.* packages on nuget? There was a small template modification and I'd like to use it.

**Comment by diegofrata** [comment]
@beorosz Done, should be available soon.

**Comment by RicoSuter** [comment]
Maybe we should setup the CI pipelines?

**Comment by beorosz** [comment]
I started to create the CI pipeline in Azure, @RicoSuter . If you wish, I can add you as project admin there.

**Comment by RicoSuter** [comment]
@beorosz can you disable your CI pipeline - so that I can take this over tomorrow and use my own pipeline (ie. it doesnt get pushed twice to nuget.org)?

**Comment by beorosz** [comment]
@RicoSuter sure, it is done. Let me know if anything wrong with the pipeline.
