### ISSUE TITLE
Create Nuget Package

### ISSUE THREAD

**Issue by TomSmith27** [RicoSuter/SigSpec#31]
As I want to use this package in my project now would it be possible to create a release in its current state so i can install a Nuget package into my project?

I noticed the Azure Devops build pipeline was already set up.

**Comment by RicoSuter** [comment]
My problem is that I dont own the CI pipeline... I'll try to move over the stuff tomorrow and release the latest packages to nuget.org

**Comment by TomSmith27** [comment]
Ok that sounds good, i am guessing you could use the GitHub Actions to do the build and release also?

**Comment by RicoSuter** [comment]
I think ill reuse my generic devops pipeline file like in the other project (public devops) - i hope i have time to set this up in the next days
